// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS9eIJJM9Wpu-iskizvqzCom74qGHPuCs',
    appId: '1:690845688972:web:85c8ddcb2bf443b25007a9',
    messagingSenderId: '690845688972',
    projectId: 'zeroto-6eac0',
    authDomain: 'zeroto-6eac0.firebaseapp.com',
    storageBucket: 'zeroto-6eac0.firebasestorage.app',
    measurementId: 'G-L6QB2BQ39Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPgbshOYWJnYe_xhQ9qQbR21j3zUSntdA',
    appId: '1:690845688972:android:2130c8e0cb36596c5007a9',
    messagingSenderId: '690845688972',
    projectId: 'zeroto-6eac0',
    storageBucket: 'zeroto-6eac0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMw2ZQWzZiJ80H8trND2cVynctCS-RFsM',
    appId: '1:690845688972:ios:8c69953b9b0e05645007a9',
    messagingSenderId: '690845688972',
    projectId: 'zeroto-6eac0',
    storageBucket: 'zeroto-6eac0.firebasestorage.app',
    iosBundleId: 'com.czappstudio.openCoreHr',
  );

}